<?php


namespace Themes\Educrat\Modules\Event\Models;


use Modules\Product\Models\Product;

class Event extends Product
{

    public $type = 'event';

    protected static function newFactory()
    {
        return \Themes\Educrat\Database\Factories\EventFactory::new(); // TODO: Change the autogenerated stub
    }
}
