<?php


namespace App;


use App\Traits\HasSEO;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class BaseTranslation extends Model
{

    use HasSEO;

    public $type = 'default';

    public function save(array $options = [])
    {
        if ($this->create_user) {
            $this->update_user = Auth::id();
        } else {
            $this->create_user = Auth::id();
        }
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
