<?php
namespace Themes\Base;

class ThemeProvider extends \Modules\Theme\Abstracts\AbstractThemeProvider
{

    public static $name = "Default Theme";

    public static $screenshot = "/default/screenshot.png";

    public static function info()
    {
        return [

        ];
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->register(RouterServiceProvider::class);
    }
}
