<?php
namespace Themes\Base;

use Modules\Core\Helpers\SettingManager;
use Modules\Vendor\VendorMenuManager;

class ThemeProvider extends \Modules\Theme\Abstracts\AbstractThemeProvider
{

    public static $name = "Default Theme";

    public static $screenshot = "/screenshot.png";

    public static function info()
    {
        return [

        ];
    }

    public function boot(){
        SettingManager::register("base_advance",[$this,'registerAdvanceSetting'],1,'base_theme');
        SettingManager::registerZone('base_theme',[$this,'registerZone']);
    }

    public function registerZone(){
        return [
            "position"=>80,
            'title'      => __("Base Settings"),
            'icon'       => 'fa fa-cogs',
            'permission' => 'setting_update',
            "group"=>"system"
        ];
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->app->register(RouterServiceProvider::class);
    }

    public function registerAdvanceSetting(){
        return [
            'id'   => 'base_theme',
            'title' => __("General Settings"),
            'position'=>80,
            'view'      => "admin.settings.general",
            "keys"      => [
                'logo_id',
                'copyright',
                'footer_info_text',
                'list_widget_footer',
                'page_contact_title',
            ],
            'filter_demo_mode'=>[
            ]
        ];
    }
}
