<?php


namespace Themes\Educrat\Modules\Course\Resources\Admin;


use App\Resources\BaseJsonResource;

class LessonResource extends BaseJsonResource
{

    public function toArray($request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
