<?php
namespace Modules\Booking;
use DemeterChain\C;
use Gloudemans\Shoppingcart\Cart;
use Modules\Product\Models\Coupon;

class BravoCart extends Cart
{
    public function getTotalDiscount(){
        $t = 0;
        $t+= $this->getCouponDiscount();
        // sau nay co the add them tax discount hoac membership discount gi do
        return $t;
    }

    public function getCouponDiscount(){
        $t = 0;
        // lay coupon ra tu session
        // doan nay chu tu code nhe
        if (!empty(session('coupon'))){
            foreach (session('coupon') as $coupon){
                $t += ($coupon['type'] == 'percent') ? parent::subtotal() * $coupon['discount']/100 : $coupon['discount'];
            }
        }
        return $t;
    }

    public function final_total($decimals = null, $decimalPoint = null, $thousandSeperator = null)
    {
        // o day minh se overide cai ham total cua no
        $total = parent::total($decimals, $decimalPoint, $thousandSeperator); // TODO: Change the autogenerated stub
//        return $this->getTotalDiscount();
        return max(0,$total - $this->getTotalDiscount());
    }
}
